name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Load dotenv from github secrets
        run: >
          echo ${{env.DOTENV_CONTENT}} > .env

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "goodrive"
          entrypoint: "main.ts"
          root: ""
