name: Deploy
env:
  CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
  PROJECT_NAME: ${{ github.ref_name == 'main' && 'goodrive' || github.ref_name == 'stage' && 'stage-goodrive' }}
  DOTENV_CONTENT: ${{ github.ref_name == 'main' && secrets.DOTENV_CONTENT || github.ref_name == 'stage' && secrets.STAGE_DOTENV_CONTENT }}

on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [main, stage]

jobs:
  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Load dotenv from github secrets
        run: >
          echo """::add-mask::${{env.DOTENV_CONTENT}}""" > .env

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{env.PROJECT_NAME}}
          entrypoint: "main.ts"
          root: ""
